apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: gitea-destination-flat
spec:
  path: backstage-catalog
  filepath:
    mode: none
  stateStoreRef:
    kind: GitStateStore
    name: default