apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: default
spec:
  authMethod: ssh
  branch: main
  gitAuthor:
    name: kratix
    email: kratix@platform.local
  secretRef:
    name: gitea-git-ssh
    namespace: default
  url: ssh://git@gitea-ssh.gitea.svc.cluster.local:22/gitea_admin/kratix.git