# Gitea Actions Runner Configuration for Podman
# Based on solution from https://gitea.com/gitea/act_runner/issues/223

log:
  level: debug

runner:
  file: .runner
  capacity: 1
  envs: {}
  env_file: .env
  timeout: 3h
  labels:
    - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
    - "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
    - "ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04"

cache:
  enabled: true

container:
  # Use "-" to indicate direct socket usage with Podman
  docker_host: "-"
  privileged: false
  options: "--add-host=host.docker.internal:host-gateway"
  workdir_parent: ""
  valid_volumes: []
  network: "host"

